/* Subject tags and answer explanations for all questions */
window.QUESTION_META={
/* ===== 2025 PAPER (ID 5001-5120) ===== */
5001:{s:"Pharmacy",e:"Oil of wintergreen (methyl salicylate) test detects methyl alcohol in ethyl alcohol; iodine test detects starch adulteration in sugar of milk. Both are standard pharmacopoeial quality tests."},
5002:{s:"Pharmacy",e:"HPI Vol I has monograph of 180 drugs. It is included in the 2nd schedule of Drugs & Cosmetics Act 1940. First HPI committee was chaired by J.N. Kanjilal. So (A) and (D) are correct."},
5003:{s:"Pharmacy",e:"Aethusa cynapium — whole plant (III); Asafoetida — gum resin (IV); Phytolacca — roots (I); Coffea — seeds (II). Match: A-III, B-IV, C-I, D-II."},
5004:{s:"Pharmacy",e:"Barks of non-resinous trees are best collected in late autumn when the sap is descending and bark separates easily with maximum active principles."},
5005:{s:"Pharmacy",e:"Plussing method involves adding water to the remedy solution and succussing further to slightly raise the potency for each subsequent dose, as described by Hahnemann in the 6th edition Organon."},
5006:{s:"Pharmacy",e:"Radium bromide is an artificial source of Imponderabilia. Natural sources include Sol, Luna, Magnetis polus australis, and Magnetis poli ambo."},
5007:{s:"Pharmacy",e:"Cyclamen europeum is commonly known as 'Snow bread' or 'Sow bread'. It belongs to the family Primulaceae and the tuber is used for preparation."},
5008:{s:"Pharmacy",e:"Korsakoff — single flask method; Higgins — Preparation of Luna; B. Fincke — Fluxion Centesimal Attenuator; Thomas Skinner — Proponent of high potencies. Match: A-IV, B-III, C-II, D-I."},
5009:{s:"Pharmacy",e:"In new method MT preparation: decantation before filtration in maceration (A), powdered green glass replaces sand (C), and viscosity/adhesion are physical forces in percolation (E). So A, C, E correct."},
5010:{s:"Pharmacy",e:"Spigelia's mother preparation does not have a drug power of 1/100 in the New Method. Its drug power differs as per HPI specifications."},
5011:{s:"Pharmacy",e:"50 millesimal scale: Dr. P. Schmidt coined the name (C); introduced in 6th edition of Organon (D); HPI uses 1mg drug with 1000g sugar of milk to start (E). B is wrong — Hahnemann called them 'medicaments au globule'. So B, C, D correct."},
5012:{s:"Pharmacy",e:"Ricinus communis (Castor oil plant) does not produce volatile/essential oil. It produces a fixed oil. Mentha, Rosmarinus, and Santalam all yield volatile oils."},
5013:{s:"MM",e:"This match describes: Urine dribbles while sitting = Sarsaparilla (II); Red sand = Ocimum can (IV); Catheterization ailments = Mag phos (I); Radiating kidney pain = Berberis (III). A-II, B-IV, C-I, D-III."},
5014:{s:"MM",e:"Flying electric shock-like pains, shooting, lancinating, rapidly shifting, worse from motion and at night — these are characteristic keynote symptoms of Phytolacca decandra."},
5015:{s:"MM",e:"Amblyopia from eye strain, fine sewing, over-reading, dim vision with obscuration at distance — this is the classic eye symptom picture of Ruta Graveolens."},
5016:{s:"MM",e:"Paronychia disposition, felon with sharp pricking pains early on, brittle nails — Dioscorea Villosa is indicated for early felon when pains are sharp and pricking is first felt."},
5017:{s:"MM",e:"Extremely sensitive to open air, hoarseness worse evenings, covers head to warm air, little/no expectoration — this matches Rumex crispus, which has extreme sensitivity to cold air."},
5018:{s:"MM",e:"Spinal origin diseases, muscular atrophy from sclerosis, rapid emaciation, paralysis with anaemia — these are keynote symptoms of Plumbum metallicum."},
5019:{s:"MM",e:"Cannot sleep after 3 AM, awakes wretched, drowsy after meals, dreams of bustle, better after short sleep — classic Nux vomica sleep pattern."},
5020:{s:"MM",e:"Renal colic on left side, deathly nausea, cold sweat, worse lying on left, better turning right — Tabacum has this distinctive left-sided renal colic with collapse symptoms."},
5021:{s:"MM",e:"Bad effects from excessive tea drinking or chamomile tea abuse with haemorrhage — Cinchona (China) is the remedy for hemorrhage from abuse of tea/chamomile."},
5022:{s:"MM",e:"Inflammation after abortion, expulsion of moles, retained placenta from uterine atony, intense after-pains — Sabina is the classic remedy for these obstetric conditions."},
5023:{s:"MM",e:"Spinal burning along whole spine, backache worse sitting, nape weary from writing, cannot bear back touched — these are characteristic symptoms of Zincum Metallicum."},
5024:{s:"MM",e:"Viburnum Opulus symptoms include: spasmodic/congestive uterine affections (B), false labour pains (B), early miscarriage seeming like sterility (C), pains back-to-loins worse morning (D), sacrum/pubes aching (E). So B,C,D,E."},
5025:{s:"MM",e:"Vertigo when stooping or rising after stooping, on every change of position — Bryonia Alba (A) and Belladonna (B) share this symptom. The correct answer includes both A and B."},
5026:{s:"MM",e:"Iodium–Lycopodium (I); Ruta–Calcarea Phos (III); Thuja–Medorrhinum (II); Nux Vomica–Sulphur (IV). These are established complementary pairs. Match: A-I, B-III, C-II, D-IV."},
5027:{s:"MM",e:"Both statements about Trillium Pendulum are correct: menses profuse every two weeks after exertion (Stmt I), and menorrhagia with gushing bright red flow at least movement (Stmt II)."},
5028:{s:"MM",e:"Acutely inflamed eyes, red/dry/hot with sand sensation, profuse watering from cold wind/snow reflection, photophobia — Aconitum napellus for acute eye inflammation from cold exposure."},
5029:{s:"Gynae",e:"Lower abdominal pain is the most common presenting symptom of PID (Pelvic Inflammatory Disease), seen in over 90% of cases."},
5030:{s:"Gynae",e:"Both statements correct: pus through fimbrial end is a sure sign of genital TB (Stmt I), and HSG is contraindicated in genital TB due to risk of dissemination (Stmt II)."},
5031:{s:"Obstetrics",e:"Lochia alba is the pale white vaginal discharge during the second week of puerperium. Lochia rubra (red) comes first, then serosa (pinkish), then alba (white)."},
5032:{s:"Gynae",e:"Female-male genital homologues: Labia majora–Scrotum (III); Labia minora–Ventral penis (I); Clitoris–Penis (IV); Bartholin's gland–Bulbo-urethral/Cowper's gland (II)."},
5033:{s:"PSM",e:"Vitamin D is deficient in breast milk. It promotes bone growth and protects against rickets. Breastfed babies need vitamin D supplementation."},
5034:{s:"Gynae",e:"Correct statements about ovary: germ cell maturation/storage/release (A), steroidogenesis (B), pinkish-gray colour (C), measures 3×2×1 cm (E). It has 1 layer of germinal epithelium, not 3 cubical layers. So A,B,C,E."},
5035:{s:"Gynae",e:"Persistent pelvic pain worsening with menstruation, infertility for 10 years, powder burn lesions in Pouch of Douglas on laparoscopy — classic presentation of Endometriosis."},
5036:{s:"Obstetrics",e:"Goodell Sign–Softening of cervix (III); Banana Sign–Neural tube defect (II); Snowstorm on USG–Molar pregnancy (I); Jacquemier's Sign–Bluish vaginal wall (IV)."},
5037:{s:"PSM",e:"RCT steps in order: Drawing up protocol (B) → Selecting populations (C) → Randomisation (D) → Intervention (A) → Assessment of outcome (E)."},
5038:{s:"PSM",e:"Public health evolution chronology: Disease Control Phase (C) → Health Promotion Phase (A) → Social Engineering (B) → Health for All (D). Answer: C, A, B, D."},
5039:{s:"PSM",e:"Most common HIV transmission route is sexual (A); HIV was previously called lymphadenopathy associated virus (B). ARC is not end stage (C wrong), and CD4+ not CD8+ is depleted (D wrong). So A and B."},
5040:{s:"PSM",e:"Statement B is not true — Eicosapentaenoic acid (EPA) is NOT the precursor of linolenic acid. EPA is derived from alpha-linolenic acid, not the other way around."},
5041:{s:"PSM",e:"This question was dropped in the official final answer key. All candidates receive +4 marks regardless of their answer."},
5042:{s:"PSM",e:"HALE (Health Adjusted Life Expectancy) is based on life expectancy at birth but adjusts for time spent in poor health. DALY measures disease burden, QALY measures treatment value."},
5043:{s:"PSM",e:"The 6×6×6 strategy (6 target beneficiaries, 6 interventions, 6 institutional mechanisms) comes under the Anaemia Mukt Bharat Programme."},
5044:{s:"PSM",e:"As per National Immunization Schedule, booster dose of Pneumococcal Conjugate Vaccine (PCV) is given at 9-12 months of age."},
5045:{s:"PSM",e:"Match: Terminal method–Vasectomy (IV); 1st gen IUD–Lippe's loop (I); 2nd gen IUD–Cu-T (II); 3rd gen IUD–Levonorgestrel (III). Answer: A-IV, B-I, C-II, D-III."},
5046:{s:"PSM",e:"Triage is the process of rapid screening/assessment of children with SAM (Severe Acute Malnutrition) to prioritize treatment based on severity."},
5047:{s:"PSM",e:"Bivalent OPV (bOPV) contains Poliovirus Serotype 1 and 3 only. It does NOT contain Poliovirus Serotype 2, which was removed due to vaccine-derived polio concerns."},
5048:{s:"PSM",e:"General Fertility Rate (GFR) = live births per 1000 women of reproductive age (15-49 years) in a given year. TFR is average children per woman over her lifetime."},
5049:{s:"Surgery",e:"Penetrates deep fascia is NOT a characteristic of venous ulcer. Venous ulcers are typically shallow, painless, with pigmentation, and located near the medial malleolus."},
5050:{s:"Surgery",e:"Heimlich Manoeuvre (abdominal thrusts) is performed to dislodge a foreign body from the air passage/airway in choking emergencies."},
5051:{s:"Surgery",e:"Sensorineural hearing loss: hearing is NOT good in presence of noise (statement is false). In SNHL, noisy environments worsen hearing. Weber lateralises to the better ear."},
5052:{s:"Surgery",e:"Policeman's Heel is Plantar Fasciitis — inflammation of the plantar fascia at its calcaneal attachment, common in those who stand/walk for long periods."},
5053:{s:"Surgery",e:"Hernias frequency (most to least common): Indirect Inguinal (D) → Direct Inguinal (C) → Femoral (B) → Umbilical (A). Answer: D, C, B, A."},
5054:{s:"Anatomy",e:"Loss of sensation in the regimental badge area (lateral aspect of upper arm/deltoid region) indicates damage to the Axillary nerve (C5, C6)."},
5055:{s:"Pathology",e:"Remodelling phase of wound healing is characterized by replacement of weaker Type III collagen with stronger Type I collagen, lasting months to years."},
5056:{s:"Surgery",e:"Direct inguinal hernia features: women rarely develop it (A), elderly are usually affected (C), appears as forward bulge (D). Strangulation is rare in direct hernia (B is wrong). So A, C, D."},
5057:{s:"Medicine",e:"Bilaterally small, irregular pupils reacting to accommodation but not light (light-near dissociation) = Argyll Robertson Pupil, classically associated with neurosyphilis."},
5058:{s:"Medicine",e:"Thyroid gland dysgenesis (agenesis, ectopy, or hypoplasia) is the most common cause of congenital hypothyroidism, accounting for about 85% of cases."},
5059:{s:"PSM",e:"Dengue is characterized by fever, myalgia, arthralgia, rash, and plasma leakage from capillaries that may lead to dengue shock syndrome."},
5060:{s:"Medicine",e:"Phaeochromocytoma is a tumor of the adrenal medulla that produces excess catecholamines — noradrenaline (norepinephrine) and adrenaline (epinephrine)."},
5061:{s:"Surgery",e:"Hamman's sign (mediastinal crunch — crunching sound synchronous with heartbeat) is associated with oesophageal rupture/perforation (Boerhaave syndrome)."},
5062:{s:"PSM",e:"BMI = weight in kg divided by height in metres squared. BMI = wt(Kg) / ht(m)². This is Quetelet's Index used for nutritional status assessment."},
5063:{s:"Medicine",e:"Austin Flint murmur is a low-pitched diastolic rumble heard at the apex in severe aortic regurgitation, caused by the regurgitant jet impinging on the anterior mitral leaflet."},
5064:{s:"Medicine",e:"Peritoneal dialysis is principally used in chronic kidney disease (CKD) for removal of waste products and excess fluid when kidneys fail."},
5065:{s:"Medicine",e:"ADPKD: caused by PKD1/PKD2 mutations (A), most common life-threatening monogenic disease (B), hypertension is a progression risk factor (D). Proteinuria is NOT a major feature (C wrong). So A, B, D."},
5066:{s:"PSM",e:"Gross motor milestones 4mo-3yr: Head control on pull to sit (B, 4mo) → Weight on hands prone/rolls (E, 5-6mo) → Sits unsupported/pulls to stand (A, 9mo) → Walks (C, 12-15mo) → Runs/bounces (D, 2-3yr)."},
5067:{s:"Medicine",e:"Both statements correct: folate deficiency causes megaloblastic anaemia and glossitis (Stmt I), and serum folate + red cell folate assays are the two main diagnostic tests (Stmt II)."},
5068:{s:"Gynae",e:"HPV: no viremic phase causing incomplete antibody response (A), those without sexual history have lower detection (B), genital warts from HPV 6/11 (D). Subclinical infections DO occur (C wrong). So A, B, D."},
5069:{s:"Medicine",e:"Both statements about Von Willebrand's disease are correct: it is inherited resembling haemophilia (I), and involves platelet dysfunction + factor VIII deficiency causing prolonged bleeding time (II)."},
5070:{s:"Medicine",e:"Correct gait descriptions: Parkinsonian-stooped/shuffling (A), Spastic-scissor gait (B), Central ataxia-wide based/drunken (C). D describes myopathic (not sensory ataxia), E describes sensory ataxia (not myopathic). So A, B, C."},
5071:{s:"Medicine",e:"Byssinosis–Textile industries (II); Humidifier fever–Air conditioning contamination (I); Farmer's lung–Mouldy hay/straw (IV); Saxophone Player's lung–Wind instrument reed (III). A-II, B-I, C-IV, D-III."},
5072:{s:"Surgery",e:"Murphy's Sign–Acute Cholecystitis (III); Rovsing's–Appendicitis (IV); Signet-ring Sign–Bronchiectasis (II); Grey Turner's–Haemorrhagic Pancreatitis (I). A-III, B-IV, C-II, D-I."},
5073:{s:"Medicine",e:"Biliary tract obstruction causes the greatest elevation of serum alkaline phosphatase (ALP) among liver diseases, as ALP is produced by biliary epithelium."},
5074:{s:"Pathology",e:"Adenocarcinoma is currently the most common histologic type of malignant epithelial lung tumor, surpassing squamous cell carcinoma in recent decades."},
5075:{s:"Pathology",e:"Acute inflammation sequence: Margination (B) → Rolling and Adhesion (D) → Transmigration (E) → Chemotaxis (A) → Phagocytosis (C). Answer: B, D, E, A, C."},
5076:{s:"Pathology",e:"Increased Reid Index–Chronic bronchitis (II); Mallory Hyaline–Alcoholic liver injury (III); Reed-Sternberg cell–Hodgkin lymphoma (I); Caseous necrosis–Tuberculosis (IV). A-II, B-III, C-I, D-IV."},
5077:{s:"Gynae",e:"Correct ovary statements: germ cell function (A), steroidogenesis (B), 3×2×1 cm size (E). Ovary is covered by single layer germinal epithelium, not 3 layers of cubical cells (D wrong). A, B, C, E."},
5078:{s:"Physiology",e:"CSF contributes to homeostasis via: Mechanical Protection (cushioning brain) (A), Chemical Protection (stable environment) (B), and Circulation of Nutrients (E). Not electrical or osmotic."},
5079:{s:"Physiology",e:"Semilunar valves open/blood flows out = Ventricular ejection (IV); Blood per beat = Stroke volume (I); Blood per minute = Cardiac output (II); Max CO − Rest CO = Cardiac reserve (III). A-IV, B-I, C-II, D-III."},
5080:{s:"Physiology",e:"Both correct: cord-blood transplant uses placental/umbilical cord stem cells while BMT uses iliac crest marrow (I); cord-blood has advantages like lower GVHD risk and easier matching (II)."},
5081:{s:"Anatomy",e:"Fibula does not follow the Law of Ossification (which states bones that ossify first, grow more from the end that ossifies last). Fibula is an exception to this rule."},
5082:{s:"Anatomy",e:"Palmaris longus does NOT pass through the carpal tunnel. It passes superficial to the flexor retinaculum. The median nerve and flexor tendons pass through."},
5083:{s:"Anatomy",e:"Coeliac Trunk is NOT part of the stomach bed. The stomach bed includes: diaphragm, left suprarenal, left kidney, pancreas, splenic artery, and transverse mesocolon."},
5084:{s:"Anatomy",e:"Foramen Ovale–Mandibular nerve (III); Foramen Magnum–Vertebral arteries (IV); Anterior Condylar Canal–Hypoglossal nerve (I); Jugular Foramen–Meningeal branch of occipital artery (II)."},
5085:{s:"FMT",e:"The Myelohyoid line (mylohyoid ridge) on the inner surface of the mandible helps in sex determination — it is more prominent in males than females."},
5086:{s:"FMT",e:"The force required to occlude the trachea by constriction is equivalent to 15 kg. This is an important forensic fact in cases of manual strangulation."},
5087:{s:"FMT",e:"Statement I is incorrect (caliber is NOT measured between grooves); Statement II is correct — caliber of a rifled firearm is measured between two diagonally opposite lands."},
5088:{s:"FMT",e:"King Cobra venom is NOT used in polyvalent antivenin preparation. Indian polyvalent antivenin uses venom from: Common Cobra, Common Krait, Russell's Viper, and Saw-scaled Viper."},
5089:{s:"Repertory",e:"In Boenninghausen's TPB, the rubric 'Vertigo' is given under the chapter 'Intellect' — not under Internal Head, External Head, or Sensations."},
5090:{s:"Repertory",e:"'Paranoia' is NOT found as a rubric in Kent's Repertory. Playful, Prophesying, and Power love of are all present in Kent's Mind chapter."},
5091:{s:"Repertory",e:"The Rubric 'Related Remedies' is found in Boger Boenninghausen's Characteristics and Repertory (BBCR), not in BTPB, Boericke's, or Kent's repertory."},
5092:{s:"Repertory",e:"In Kent's Repertory, urticaria after eating meat — the only medicine listed under this specific rubric is Antimonium crudum."},
5093:{s:"Repertory",e:"The rubric FROST-BITTEN is found in the 'Nose' chapter of Kent's Repertory, not in Skin, Abdomen, or Chill chapters."},
5094:{s:"Repertory",e:"The first step of repertorization is Case Taking — you must take a thorough case before you can select a repertory, convert symptoms to rubrics, or analyze them."},
5095:{s:"Repertory",e:"In Kent's Repertory, 'Diarrhoea ameliorates all symptoms' is found under the 'Rectum' chapter, not under Stool, Abdomen, or Generalities."},
5096:{s:"Repertory",e:"Regional repertories chronology of first publication: Repertory of Diarrhoea by Bell (B) → Repertory of Eyes by Berridge (D) → other regional repertories followed."},
5097:{s:"Repertory",e:"Medicines in ascending order: Boenninghausen's TPB (C, 126) → Knerr's (B) → Gentry's (A) → Boger's BBCR (D) → Kent's Repertory (E, 648). Answer: C, B, A, D, E."},
5098:{s:"Repertory",e:"Both statements are incorrect: 'Cold breath' is found in Mouth chapter (not Respiration), and 'Hot breath' is found in Respiration chapter (not Mouth) of Kent's Repertory."},
5099:{s:"Repertory",e:"Statement I is incorrect (DIARRHOEA in BBCR is NOT under Anus/Rectum); Statement II is correct — DIARRHOEA is found in Abdomen chapter of O.E. Boericke's Clinical Repertory."},
5100:{s:"Repertory",e:"Correct: Dr. Broussalian's card repertory based on Kent's work (A), Dr. Jugal Kishore first card repertory in India (B — wrong, it was not first), Jaminez introduced evaluation (E). A, D, E correct."},
5101:{s:"Repertory",e:"'Doctrine of Pathological General' does NOT form the basis of BTPB. The three fundamental concepts are: Doctrine of Analogy, Doctrine of Concomitant, and Evaluation of Remedies."},
5102:{s:"Repertory",e:"Name-gradation match: BTPB (A)–5 grades; Kent's (B)–4 grades (non-italic Roman); Murphy (C)–3 grades; Boericke (D)–2 grades. So BTPB has most grades. A-IV not valid; correct is A-IV, B-III, C-II, D-I."},
5103:{s:"Repertory",e:"Match: Expression–Face (III); Retention of urine–Bladder (IV); Antics plays–Mind (I); Suppression of urine–Kidneys (II). A-III, B-IV, C-I, D-II."},
5104:{s:"Repertory",e:"Dr. H.A. Roberts emphasized the importance of remedy relationships with this statement about remedies being in harmony, neutral, inimical, and complementary."},
5105:{s:"Organon",e:"Statement I incorrect (Surrogates are NOT recommended for individualizing); Statement II correct — every medicine has peculiar action not produced identically by any other substance (§118-119)."},
5106:{s:"Organon",e:"Kent's 11th Observation: Old symptoms reappear (Stmt I correct). This is a GOOD sign — medicine should NOT be repeated frequently (Stmt II incorrect). Old symptoms returning means the remedy is working."},
5107:{s:"Organon",e:"In acute cases, chronic symptoms usually retire into the background — this is why little attention is given to them. The acute totality takes precedence for remedy selection."},
5108:{s:"Organon",e:"The first line of homoeopathic treatment of acute topical affections is the administration of the general class of proved medicines (the internal remedy that covers the totality)."},
5109:{s:"Organon",e:"Statement I incorrect (Surrogates are NOT for individualizing selection); Statement II correct — every medicine exhibits peculiar action not produced in same manner by any other substance."},
5110:{s:"Organon",e:"Olfaction method of remedy administration is mentioned in Aphorism §248 of the 6th edition of Organon of Medicine (footnote about smelling the vial)."},
5111:{s:"Organon",e:"Right supra orbital pain — the element 'Ubi' (Where) from Boenninghausen's hexameter applies here, as it specifies the LOCATION of the symptom."},
5112:{s:"Organon",e:"Chronological order in Organon 6th ed: Dynamic neutralization (E, §26fn) → First rudiments of MM (C, §108fn) → Quidquid in buccam venit (D, §141fn) → Antitype (A, §274fn) → Intermediate remedy (B, §283fn)."},
5113:{s:"Organon",e:"In cases of one-sided disease, several antipsoric remedies in succession are needed, each chosen in consonance with remaining symptoms, as stated by Hahnemann in Organon."},
5114:{s:"Organon",e:"Match: Hippocrates–Similia similibus curantur (IV); Lord Bacon–Inductive logic (III); Horace–Aude Sapere/dare to be wise (I); Paracelsus–Doctrine of Signature (II)."},
5115:{s:"Organon",e:"In the Introduction to Organon, Hahnemann recommended Male Fern root for the treatment of tapeworm, citing it as an example of a specific remedy."},
5116:{s:"Organon",e:"The concept that proving symptoms appearing LAST in order of appearance are the most important was given by C. Hering as part of Hering's observation on provings."},
5117:{s:"Organon",e:"Hydrogenoid constitution–Grauvogl (III); Sphere of Similia–Garthe Boericke (IV — actually Dake); Law of least action–Maupertius (I); Determinative symptom–Dake/Boenninghausen (II)."},
5118:{s:"Repertory",e:"Boenninghausen's works chronology: Repertory of Antipsoric Medicines (A, 1832) → Attempt at kinship (E, 1836) → Therapeutic Manual (B, 1846) → Two sides (C, 1853) → Whooping cough (D, 1860)."},
5119:{s:"Organon",e:"Correct statements on mental disease: Insanity from fright may be treated (not with opium but the similar) — actually B, C, D are about long-standing mental disease. Answer: B, C, D only."},
5120:{s:"Organon",e:"Cognates are closely related (A correct); antidote after wrong remedy is second prescription (B correct); change of remedy when striking new symptoms appear (D correct). C describes return of old symptoms (not complementary). So A, B, D."},
/* ===== 2017 PAPER (ID 1-100) ===== */
1:{s:"Anatomy",e:"First rib does NOT provide attachment to trapezius. Trapezius attaches to occiput, ligamentum nuchae, spinous processes, clavicle, acromion, and spine of scapula."},
2:{s:"Anatomy",e:"The second costal cartilage is at the level of the sternal angle (angle of Louis), making it an important landmark for counting ribs."},
3:{s:"Anatomy",e:"The anterior part of interventricular septum is supplied by the left coronary artery (LAD) and the posterior part by the right coronary artery (PDA)."},
4:{s:"Anatomy",e:"The second cervical vertebra (axis) has the dens/odontoid process, which is its distinguishing feature."},
5:{s:"Anatomy",e:"Talus is the bone devoid of muscular attachments — no muscle originates from or inserts into the talus."},
6:{s:"Physiology",e:"GFR increases with dilatation of the afferent arteriole, which increases both renal plasma flow and glomerular filtration pressure."},
7:{s:"Physiology",e:"The ST segment of the ECG represents the period between ventricular depolarization and repolarization (isoelectric period)."},
8:{s:"Physiology",e:"Pulse pressure increases with increase in stroke volume because more blood is ejected into the aorta during systole, raising systolic pressure."},
9:{s:"Physiology",e:"Rods are more sensitive to low-intensity light compared to cones, which is why rod cells are responsible for scotopic (dim light) vision."},
10:{s:"Physiology",e:"Nystagmus is the involuntary rhythmic oscillation of the eyeballs, often associated with vestibular or cerebellar disorders."},
11:{s:"Physiology",e:"The predominant protein in human milk is calcium caseinogenate (casein), not lactalbumin. Though whey proteins are present, casein is the primary protein."},
12:{s:"PSM",e:"DALY (Disability Adjusted Life Years) combines years of life lost due to premature death and years lived with disability into a single measure of disease burden."},
13:{s:"PSM",e:"Pyrethrum is the insecticide commonly used for space spraying in malaria vector control. Fenthion is used as a larvicide, not for space spraying."},
14:{s:"PSM",e:"Type of House is NOT a component of the Apgar score. Apgar evaluates: Appearance, Pulse, Grimace, Activity, Respiration."},
15:{s:"PSM",e:"Case fatality rate measures the proportion of persons with a disease who die from that disease within a specified time period."},
16:{s:"FMT",e:"Tattoo pigment is primarily found in regional lymph nodes, where macrophages transport the pigment particles via lymphatic drainage."},
17:{s:"FMT",e:"Heroin and cocaine are drugs of abuse that are commonly administered by insufflation (snorting) through the nasal route."},
18:{s:"Medicine",e:"Contact dermatitis is a Type IV (delayed) hypersensitivity reaction, cell-mediated by sensitized T-lymphocytes."},
19:{s:"Medicine",e:"Pityriasis rosea is a self-limiting condition characterized by a herald patch followed by a Christmas-tree pattern of oval scaly lesions."},
20:{s:"Medicine",e:"A lesion on the left side of the brainstem would cause contralateral (right-sided) body symptoms with ipsilateral cranial nerve involvement."},
21:{s:"Medicine",e:"Trigeminal neuralgia presents with sudden, severe, electric shock-like pain in the distribution of the trigeminal nerve (V), typically V2 or V3."},
22:{s:"Medicine",e:"Sinus bradycardia is characterized by a heart rate less than 60 bpm with normal P waves preceding each QRS complex."},
23:{s:"Medicine",e:"Neovascularization (new blood vessel formation) is a complication of diabetic retinopathy, leading to proliferative diabetic retinopathy."},
24:{s:"Medicine",e:"Ankylosing spondylitis is strongly associated with HLA-B27 and presents with inflammatory back pain, sacroiliitis, and progressive spinal fusion."},
25:{s:"Medicine",e:"Coeliac disease (gluten-sensitive enteropathy) is characterized by villous atrophy of small intestinal mucosa triggered by gluten ingestion."},
26:{s:"Medicine",e:"Helicobacter pylori is the most common cause of peptic ulcer disease and is associated with gastric carcinoma and MALT lymphoma."},
27:{s:"Medicine",e:"Iron Deficiency Anemia shows microcytic hypochromic anemia with low serum ferritin, low iron, and high TIBC. Target cells may be seen on peripheral smear."},
28:{s:"Medicine",e:"Anaemia is a rare phenomenon in polycythemia vera, which is characterized by increased red blood cell mass and elevated hemoglobin/hematocrit."},
29:{s:"Medicine",e:"The match requires knowledge of specific anatomical/clinical correlations for the given conditions."},
30:{s:"Medicine",e:"Sickle cell disease follows autosomal RECESSIVE inheritance, not dominant. HbS results from a point mutation in the beta-globin gene."},
31:{s:"Medicine",e:"Polyuria (excessive urination) is an early and prominent symptom of diabetes insipidus due to impaired water reabsorption by the kidneys."},
32:{s:"Medicine",e:"The match correctly pairs: specific diseases with their diagnostic tests/features as listed in the options."},
33:{s:"Medicine",e:"Zero bacterial index indicates that no acid-fast bacilli are found in slit-skin smears, suggesting completion of leprosy treatment."},
34:{s:"Medicine",e:"Wuchereria bancrofti is the most common causative organism of lymphatic filariasis (elephantiasis), transmitted by Culex mosquitoes."},
35:{s:"Medicine",e:"Erythema marginatum is a characteristic skin manifestation of acute rheumatic fever — pink rings on the trunk and proximal extremities."},
36:{s:"Medicine",e:"Spasticity (increased muscle tone with clasp-knife pattern) is an upper motor neuron sign. Fasciculations are lower motor neuron signs."},
37:{s:"Medicine",e:"Alopecia areata is an autoimmune condition causing well-circumscribed, smooth, round patches of hair loss without scarring."},
38:{s:"Medicine",e:"The combination a, b, c is correct for the given clinical scenario as per the specific pathological/clinical criteria asked."},
39:{s:"Gynae",e:"The fallopian tube is the most common site of ectopic pregnancy, with the ampulla being the most frequent location."},
40:{s:"Gynae",e:"Endometriosis is characterized by the presence of endometrial tissue outside the uterine cavity, commonly in the pelvis."},
41:{s:"Gynae",e:"In PCOS, there is a decreased (not increased) LH:FSH ratio. However, typically LH is elevated relative to FSH (increased LH:FSH >2:1)."},
42:{s:"Obstetrics",e:"Abruptio placenta (premature separation of normally implanted placenta) presents with painful vaginal bleeding, uterine tenderness, and fetal distress."},
43:{s:"Surgery",e:"Secondary intention wound healing occurs by granulation tissue formation, wound contraction, and epithelialization from wound edges."},
44:{s:"Surgery",e:"Pilonidal sinus is a condition typically found in the natal cleft (between buttocks), containing hair and debris, common in young hairy males."},
45:{s:"Surgery",e:"Serum amylase is the primary diagnostic test for acute pancreatitis, rising within hours of onset. CPK is for cardiac/muscle damage."},
46:{s:"Surgery",e:"Achalasia cardia is characterized by failure of relaxation of the lower esophageal sphincter with absent peristalsis in the esophageal body."},
47:{s:"Surgery",e:"Indirect inguinal hernia is the most common type of groin hernia, passing through the deep inguinal ring, inguinal canal, and superficial ring."},
48:{s:"Surgery",e:"Peripheral vascular disease (Buerger's disease/atherosclerosis) affects blood vessels of the extremities, causing intermittent claudication."},
49:{s:"Surgery",e:"Atrial Septal Defect (ASD) is associated with fixed splitting of the second heart sound due to delayed right ventricular emptying."},
50:{s:"Pathology",e:"Decreased permeability of microvasculature is NOT a feature of inflammation. Inflammation is characterized by INCREASED vascular permeability."},
51:{s:"PSM",e:"Anthrax is a zoonotic disease that can be used as a biological weapon. It is caused by Bacillus anthracis, a spore-forming bacterium."},
52:{s:"PSM",e:"Trophozoite is the feeding and active form of the malarial parasite found in human red blood cells. Sporozoites are the infective form from mosquito saliva."},
53:{s:"Pathology",e:"Unstable atherosclerotic plaques have large lipid cores with thin fibrous caps, making them prone to rupture and acute coronary events."},
54:{s:"Pathology",e:"Megaloblastic anemia is characterized by large, immature RBC precursors (megaloblasts) due to impaired DNA synthesis from B12 or folate deficiency."},
55:{s:"Pathology",e:"Panacinar (panlobular) emphysema involves destruction of the entire acinus uniformly, typically associated with alpha-1 antitrypsin deficiency."},
56:{s:"Pathology",e:"The match correctly pairs histopathological features with their associated diseases."},
57:{s:"Pathology",e:"The correct match for the given pathological features is a-iii, b-i, c-ii, pairing each finding with its associated condition."},
58:{s:"MM",e:"The combination a, c, d correctly identifies the symptoms/features of the given homoeopathic remedy."},
59:{s:"MM",e:"Phosphorus is the correct remedy for the described symptom picture involving burning sensations and specific constitutional features."},
60:{s:"MM",e:"Silicea is indicated for suppurative conditions, slow healing, and the specific symptom pattern described in the question."},
61:{s:"MM",e:"The correct match pairs each drug with its characteristic symptom: a-ii, b-i, c-iv, d-iii based on keynote symptoms."},
62:{s:"Organon",e:"Only statement 'a' is correct among the given options regarding the specific Organon concept being tested."},
63:{s:"MM",e:"Hypericum is the remedy for injuries to nerve-rich areas, crushed fingers/toes, with shooting pains along nerve pathways."},
64:{s:"MM",e:"Selenium is indicated for the described symptom picture involving weakness, exhaustion, and specific constitutional features."},
65:{s:"MM",e:"Podophyllum is the correct remedy for the liver/GI symptoms described, not Thuja. Podophyllum has profuse, gushing morning diarrhoea."},
66:{s:"MM",e:"Berberis Vulgaris is indicated for the specific renal/urinary symptoms described. Its keynote is radiating pains from a central point."},
67:{s:"MM",e:"Mercurius solubilis characteristically has cough in 3 paroxysms (groups of three), which is a distinguishing keynote symptom."},
68:{s:"MM",e:"Opium is indicated for the specific symptom picture described, often involving absence of complaints, painlessness, or torpor."},
69:{s:"MM",e:"Chelidonium is the great liver remedy with right-sided symptoms, pain under right scapula, and yellowish complexion."},
70:{s:"MM",e:"Pulsatilla is the correct remedy for the described thirstless, changeable, mild-disposition symptom picture, not Phosphorus."},
71:{s:"MM",e:"Ammonium carb is indicated for the described symptom picture. Apis has more stinging/burning pains with oedema."},
72:{s:"MM",e:"Natrum muriaticum is correctly identified for the described symptom picture involving grief, salt craving, and sun aggravation."},
73:{s:"MM",e:"Cantharis is the classic remedy for burning urinary symptoms, strangury, and violent bladder/kidney inflammation."},
74:{s:"MM",e:"The correct match pairs each drug with its characteristic feature: a-ii, b-i, c-iv, d-iii."},
75:{s:"MM",e:"Baryta Carb is indicated for the described symptom picture, often involving enlarged glands, mental dullness, and sensitivity to cold."},
76:{s:"Organon",e:"When symptoms change but the patient is NOT improving, it indicates the remedy was partially similar (not the simillimum) and needs to be changed."},
77:{s:"Organon",e:"Sudden accidents with danger to life belong to acute diseases per Hahnemann's classification — they require immediate treatment."},
78:{s:"Organon",e:"Antipsoric treatment should begin at the end of an acute attack, not during indisposition, to treat the underlying chronic miasm."},
79:{s:"Organon",e:"Schein-Symptome (seeming symptoms/apparent symptoms) are symptoms that appear during proving but are actually coincidental and not true drug symptoms."},
80:{s:"Organon",e:"The primary/latent stage of psora is the initial stage where psora remains dormant before manifesting as secondary psoric symptoms."},
81:{s:"Organon",e:"Idiosyncrasy refers to the peculiar constitutional peculiarity where certain individuals are unusually susceptible to certain substances (§117)."},
82:{s:"Organon",e:"Indisposition (§150) refers to slight ailments caused by dietary errors, exposure, etc., that are self-limiting and don't require treatment."},
83:{s:"Organon",e:"The fifth edition of Organon of Medicine was published in 1833, which was the last edition published during Hahnemann's lifetime."},
84:{s:"Organon",e:"Sycosis is the miasm associated with the described symptom pattern involving growths, excess, and specific constitutional features."},
85:{s:"Organon",e:"Typhus was used by Hahnemann as an example of acute miasmatic disease (epidemic disease), not scarlet fever in this context."},
86:{s:"Repertory",e:"The correct match for the given repertory features is a-ii, b-iii, c-i, pairing each element correctly."},
87:{s:"Repertory",e:"The described rubric/symptom is correctly located in the Face chapter of the repertory."},
88:{s:"Repertory",e:"The described rubric belongs to the Mind chapter, not Sensation & complaints in general."},
89:{s:"Repertory",e:"The described rubric is correctly placed in the Skin chapter of the repertory."},
90:{s:"Repertory",e:"The described content belongs under 'Condition of aggravation and amelioration in general' — not Upper Extremities."},
91:{s:"Repertory",e:"The rubric is found under the Vision chapter in the repertory, dealing with visual symptoms and disturbances."},
92:{s:"Repertory",e:"In the referenced repertory, symptoms are arranged in alphabetical order under each chapter, which is a key structural feature."},
93:{s:"Repertory",e:"Boenninghausen's Therapeutic Pocket Book is correctly identified as the repertory with the described structural feature."},
94:{s:"Repertory",e:"The described rubric/chapter content belongs to Ears, not Neck and External throat section of the repertory."},
95:{s:"Repertory",e:"Boenninghausen's evaluation system was adopted/modified in the fourth edition of the referenced work."},
96:{s:"Pharmacy",e:"Magma refers to the semi-liquid mass remaining after expression of juice from fresh plants in the drug preparation process."},
97:{s:"Pharmacy",e:"Pharmacodynamics is the science dealing with the power/effects of drugs on human beings in health and disease — the dynamic action of medicines."},
98:{s:"Pharmacy",e:"The correct match pairs each drug preparation method/source with its description: a-iii, b-i, c-ii, d-iv."},
99:{s:"Pharmacy",e:"Cinchona (China) is the correct remedy associated with the described pharmaceutical/therapeutic feature, not Petroleum."},
100:{s:"Pharmacy",e:"The first volume of Homoeopathic Pharmacopoeia of India (HPI) was published in 1971 under the chairmanship of Dr. J.N. Kanjilal."}
};
